// Module2_FrontendDev/handson_08/src/App.vue
<script setup>
import Header from './components/Header.vue';
</script>

<template>
  <Header site-name="Student Portal" />

  <main class="container page-main">
    <RouterView />
  </main>

  <footer class="site-footer">
    <div class="container">
      <p>&copy; 2026 Student Portal. Built with Vue 3 for Digital Nurture 5.0.</p>
    </div>
  </footer>
</template>

<style scoped>
.page-main {
  min-height: 60vh;
  padding-top: 2rem;
  padding-bottom: 2rem;
}

.site-footer {
  margin-top: 3rem;
  padding: 1.5rem 0;
  background: var(--color-surface);
  border-top: 1px solid var(--color-border);
  color: var(--color-muted);
  font-size: 0.9rem;
  text-align: center;
}
</style>

// Module2_FrontendDev/handson_10/src/App.jsx
import { Routes, Route } from 'react-router-dom';
import Header from './components/Header';
import ErrorBoundary from './components/ErrorBoundary';
import CoursesPage from './pages/CoursesPage';
import CourseDetailPage from './pages/CourseDetailPage';
import ProfilePage from './pages/ProfilePage';

function App() {
  return (
    <>
      <Header siteName="Student Portal" />

      <main className="container page-main">
        <ErrorBoundary>
          <Routes>
            <Route path="/" element={<CoursesPage />} />
            <Route path="/courses/:courseId" element={<CourseDetailPage />} />
            <Route path="/profile" element={<ProfilePage />} />
          </Routes>
        </ErrorBoundary>
      </main>

      <footer className="site-footer">
        <div className="container">
          <p>&copy; 2026 Student Portal. Built with React + Redux Toolkit for Digital Nurture 5.0.</p>
        </div>
      </footer>
    </>
  );
}

export default App;
