// Module2_FrontendDev/handson_05/src/components/Header.jsx
// Task 1, Step 62-64: functional component receiving props.
function Header({ siteName, enrolledCount = 0 }) {
  return (
    <header className="app-header">
      <p className="brand">{siteName}</p>
      <nav aria-label="Main navigation">
        <ul className="nav-links">
          <li>Home</li>
          <li>Courses</li>
          <li>Profile ({enrolledCount})</li>
        </ul>
      </nav>
    </header>
  );
}

export default Header;

// Module2_FrontendDev/handson_07/src/app/components/header/header.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent {
  @Input() siteName = 'Student Portal';
}

<header class="app-header">
  <div class="container header-inner">
    <a routerLink="/" class="brand">{{ siteName }}</a>

    <nav aria-label="Main navigation">
      <ul class="nav-links">
        <li><a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">Courses</a></li>
        <li><a routerLink="/profile" routerLinkActive="active">Profile</a></li>
      </ul>
    </nav>
  </div>
</header>
