// Module2_FrontendDev/handson_10/src/components/Header.jsx
import { Link, NavLink } from 'react-router-dom';
import { useSelector } from 'react-redux';
import { selectEnrolledCount } from '../store/enrollmentSlice';

function Header({ siteName = 'Student Portal' }) {
  const enrolledCount = useSelector(selectEnrolledCount);

  return (
    <header className="app-header">
      <div className="container header-inner">
        <Link to="/" className="brand">
          {siteName}
        </Link>

        <nav aria-label="Main navigation">
          <ul className="nav-links">
            <li>
              <NavLink to="/" end className={({ isActive }) => (isActive ? 'active' : '')}>
                Courses
              </NavLink>
            </li>
            <li>
              <NavLink to="/profile" className={({ isActive }) => (isActive ? 'active' : '')}>
                Profile ({enrolledCount})
              </NavLink>
            </li>
          </ul>
        </nav>
      </div>
    </header>
  );
}

export default Header;

// Module2_FrontendDev/handson_07/src/app/components/header/header.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-header',
  templateUrl: './header.component.html',
  styleUrls: ['./header.component.css'],
})
export class HeaderComponent {
  @Input() siteName = 'Student Portal';
}

<header class="app-header">
  <div class="container header-inner">
    <a routerLink="/" class="brand">{{ siteName }}</a>

    <nav aria-label="Main navigation">
      <ul class="nav-links">
        <li><a routerLink="/" routerLinkActive="active" [routerLinkActiveOptions]="{ exact: true }">Courses</a></li>
        <li><a routerLink="/profile" routerLinkActive="active">Profile</a></li>
      </ul>
    </nav>
  </div>
</header>
