// Module2_FrontendDev/handson_06/src/components/CourseCard.jsx
function CourseCard({ id, name, code, credits, grade, onSelect }) {
  return (
    <article
      className="course-card"
      tabIndex={0}
      role="button"
      onClick={() => onSelect(id)}
      onKeyDown={(e) => {
        if (e.key === 'Enter' || e.key === ' ') {
          e.preventDefault();
          onSelect(id);
        }
      }}
    >
      <h3>{name}</h3>
      <p className="course-code">{code}</p>
      <p className="course-credits">{credits} credits</p>
      {grade && <p className="course-grade">Grade: {grade}</p>}
    </article>
  );
}

export default CourseCard;

// Module2_FrontendDev/handson_07/src/app/components/course-card/course-card.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'app-course-card',
  templateUrl: './course-card.component.html',
  styleUrls: ['./course-card.component.css'],
})
export class CourseCardComponent {
  @Input() id!: number;
  @Input() name!: string;
  @Input() code!: string;
  @Input() credits!: number;
  @Input() grade?: string;

  @Output() select = new EventEmitter<number>();

  onActivate(): void {
    this.select.emit(this.id);
  }

  onKeydown(event: KeyboardEvent): void {
    // Keyboard accessibility: Enter or Space activates the card,
    // matching what a mouse click would do (Hands-On 9 pattern).
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      this.onActivate();
    }
  }
}

<article
  class="course-card"
  tabindex="0"
  role="button"
  [attr.aria-label]="name + ', ' + credits + ' credits'"
  (click)="onActivate()"
  (keydown)="onKeydown($event)"
>
  <h3>{{ name }}</h3>
  <p class="course-code">{{ code }}</p>
  <p class="course-credits"><span>{{ credits }}</span> credits</p>
  <p class="course-grade" *ngIf="grade">Grade: <strong>{{ grade }}</strong></p>
</article>
